---
##
# Configure the rabbit queue
##

- block:

  - name: TEMPLATE | Apply rabbitmq-env.conf template
    template:
      src: "rabbitmq-env.conf.j2"
      dest: "{{ rabbitmq_config }}"
      owner: root
      group: root
      mode: 0644
    notify: restart rabbitmq

  when: rabbitmq_enabled

- meta: flush_handlers
