---
##
# Setup RabbitMQ
##

##
# Import variable definitions and defaults
##
- name: IMPORT_TASKS | Setup Variable definitions / defaults
  import_tasks: setup-variables.yml

##
# Setup the OS based on family
##
- name: IMPORT_TASKS | Setup percona mysql for OS
  import_tasks: "setup-Debian.yml"
  when:
    - ansible_facts['os_family'] == 'Debian'

##
# Configuration and setup
##
- name: IMPORT_TASKS | Configure rabbitmq
  import_tasks: "configure-rabbitmq.yml"

- name: IMPORT_TASKS | Setup plugins
  import_tasks: "setup-plugins.yml"
