---
#
# Default OS specific variable definitions / defaults
#
- block:
  - name: INCLUDE_VARS | OS specific vars
    include_vars: "{{ ansible_facts['os_family'] }}.yml"

  - name: FACTS - Define RabbitMQ package dependencies
    set_fact:
      rabbitmq_packages: "{{ __rabbitmq_packages | list }}"
    when: rabbitmq_packages is not defined

  - name: FACTS - Define the RabbitMQ service / daemon
    set_fact:
      rabbitmq_service: "{{ __rabbitmq_service }}"
    when: rabbitmq_service is not defined

  - name: FACTS - Define RabbitMQ config file
    set_fact:
      rabbitmq_config: "{{ __rabbitmq_config }}"
    when: rabbitmq_config is not defined

  when: rabbitmq_enabled
